export type ValidFont =
  | "classic"
  | "future"
  | "square"
  | "subscript"
  | "superscript"
  | "upsidedown"
  | "cursive"
  | "double-struck"
  | "circle"
  | "parenthesized"
  | "asian-like"
  | "bold"
  | "italic"
  | "wide"
  | "runic";
